// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxhfwqxytkvztzdjfwuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4aGZ3cXh5dGt2enR6ZGpmd3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU4MzksImV4cCI6MjA2NTUwMTgzOX0.qEI63UqolnvP6BY4lXm-ixV3VNNEWDCZhQ-wPWCEAF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Configurar sessão simulada se existir no localStorage
if (typeof window !== 'undefined') {
  const savedSession = localStorage.getItem('auth_session');
  if (savedSession) {
    try {
      const parsedSession = JSON.parse(savedSession);
      // Verificar se a sessão não expirou
      if (parsedSession.expires_at > Math.floor(Date.now() / 1000)) {
        supabase.auth.setSession(parsedSession);
      }
    } catch (error) {
      console.log('Erro ao configurar sessão:', error);
    }
  }
}