// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Configurar sessão simulada se existir no localStorage
if (typeof window !== 'undefined') {
  const savedSession = localStorage.getItem('auth_session');
  if (savedSession) {
    try {
      const parsedSession = JSON.parse(savedSession);
      // Verificar se a sessão não expirou
      if (parsedSession.expires_at > Math.floor(Date.now() / 1000)) {
        supabase.auth.setSession(parsedSession);
      }
    } catch (error) {
      console.log('Erro ao configurar sessão:', error);
    }
  }
}